item {
 id: 8337 
 name: 'Cap1' 
}
item {
 id: 8338 
 name: 'Cap2' 
}
item {
 id: 8339 
 name: 'Cap3' 
}
item {
 id: 8340 
 name: 'Cap4' 
}
item {
 id: 8341 
 name: 'MOSFET' 
}
item {
 id: 8342 
 name: 'Mov' 
}
item {
 id: 8343 
 name: 'Resestor' 
}
item {
 id: 8344 
 name: 'Resistor' 
}
item {
 id: 8345 
 name: 'Transformer' 
}